token = "" # Токен сообщества ВКонтакте

user_id = "" # Ваш логин
user_password = "" # Ваш пароль

ID_user_to_add = "" # ID пользователя, которого хотите добавить
ID_your = "" # Ваш ID
ID_chat = "" # ID чата
